### ISSUE TITLE
How to evaluate the effect of heterozygous SNP and homozygous SNP on TF binding

### ISSUE THREAD

**Issue by caokai001** [Boyle-Lab/SEM_CPP#15]
>  #   Good work!

>  i have a small question about the sempl sorfware.
> such as fig 2D in this paper ,when change the pos8 to C for  HNF4A motif,the TF binding will ablated.

>  How do I evaluate TF binding when I consider heterozygous mutations and homozygous mutations? such as  `C/C` and `A/C` at pos 8.
>    I thank `C/C `at pos 8 cause transcription factors to fall off, and `A/C` at pos 8  lead to reduced affinity of transcription factors,the chip signal maybe be the half  of `A/A`. is it correct?

 

>   Looking forward to your reply, thanks.

![](https://github.com/caokai001/Bioinformatic_code/blob/master/%E4%BB%93%E5%BA%93/Snipaste_2019-07-16_15-31-41.png?raw=true)

**Comment by aboyle** [comment]
I do think that this is an appropriate interpretation.
